### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by viktorot** [viktorot/notefy#1]
- [ ] notification PendingIntent to edit note
- [ ] more icons
- [ ] splash screen
- [ ] delete undo
- [ ] scrolling down should hide the fab
- [ ] share text/link
